### ISSUE TITLE
使用 docker 部署 Upsource 错误

### ISSUE THREAD

**Issue by oustn** [ja-netfilter/ja-netfilter#101]
参考这个 https://zhile.io/2022/01/13/youtrack-upsource-hub-via-power.html 

ja-netfilter-v2.2.3

```
FROM jetbrains/upsource:2020.1.1970

COPY ./ja-netfilter /ja
RUN /run.sh configure -J"-javaagent:/ja/ja-netfilter.jar" && \
    cp /opt/upsource/conf/upsource.jvmoptions /opt/upsource/conf/upsource-frontend/upsource-frontend.jvmoptions && \
    cp /opt/upsource/conf/upsource.jvmoptions /opt/upsource/conf/upsource-cluster-init/upsource-cluster-init.jvmoptions

ENTRYPOINT ["/bin/bash", "/run.sh"]
```

upsource-frontend 服务一直重启

upsource-cluster-init:   ============================================================================
upsource-cluster-init:
upsource-cluster-init:     ja-netfilter-v2.2.3
upsource-cluster-init:
upsource-cluster-init:     A javaagent framework :)
upsource-cluster-init:
upsource-cluster-init:     https://github.com/ja-netfilter/ja-netfilter
upsource-cluster-init:
upsource-cluster-init:   ============================================================================
upsource-cluster-init:
upsource-cluster-init: Loading Upsource properties file: /opt/upsource/conf/upsource-cluster-init/upsource.properties
upsource-cluster-init: Upsource properties file /opt/upsource/conf/upsource.user.properties not found!
upsource-cluster-init: Writing logs to /opt/upsource/logs/upsource-cluster-init
upsource-cluster-init: Using logs configuration from /opt/upsource/conf/upsource-cluster-init/log4j.xml.dist
upsource-cluster-init: [Upsource Cluster Initialize Service Error] [2022-02-14 09:59:47,778] WARN  SMTPSettingsUpdate-1                 ettings.api.StaticMailSettings - This mail service is disabled
upsource-cluster-init: [Upsource Cluster Initialize Service Error] [2022-02-14 09:59:47,781] WARN  SMTPSettingsUpdate-1                 ettings.api.StaticMailSettings - From address is empty
upsource-cluster-init: Upsource Cluster Initialize Service is running
* Starting Upsource Frontend
upsource-frontend: Starting Upsource Frontend...
upsource-frontend:
upsource-frontend:   ============================================================================
upsource-frontend:
upsource-frontend:     ja-netfilter-v2.2.3
upsource-frontend:
upsource-frontend:     A javaagent framework :)
upsource-frontend:
upsource-frontend:     https://github.com/ja-netfilter/ja-netfilter
upsource-frontend:
upsource-frontend:   ============================================================================

**Comment by pengzhile** [comment]
什么错误？非docker下会不会错误？

**Comment by oustn** [comment]
> 

我在 mac 下试过是正常的，frontend 服务报错误退出，没有明显的错误堆栈信息

**Comment by pengzhile** [comment]
我就是mac环境下测试的，没问题啊

**Comment by oustn** [comment]
> 我就是mac环境下测试的，没问题啊

你要不试下官方docker镜像看看？jetbrains/upsource:2020.1.1970   我物理机上确实也可以，而且很奇怪 没有清晰的错误信息。。
