### ISSUE TITLE
可以在linux用吗

### ISSUE THREAD

**Issue by wslqm** [ja-netfilter/ja-netfilter#105]

**Comment by wslqm** [comment]
可以在linux用吗

**Comment by GreyXor** [comment]
Yes

**Comment by pengzhile** [comment]
完全可以

**Comment by lrbmike** [comment]
@pengzhile 测试最新版本的idea2022.1的linux版本不行，因为脚本启动jdk环境默认用的是自带的jbr11，默认目前jar插件不支持11版本。尝试通过idea配置调整启动的java环境版本为jdk8(Help -> Find Action -> Choose Boot Java Runtime for the IDE)，但是提示必须要使用不低于jdk11的版本

**Comment by pengzhile** [comment]
> @pengzhile 测试最新版本的idea2022.1的linux版本不行，因为脚本启动jdk环境默认用的是自带的jbr11，貌似目前jar插件不支持11版本。尝试通过idea配置调整启动的java环境版本为jdk8(Help -> Find Action -> Choose Boot Java Runtime for the IDE)，但是提示必须要使用不低于jdk11的版本

你能在关闭的issues里找，为什么对置顶的issue视而不见？？？明确的说java11完美支持。
