### ISSUE TITLE
tomcat这种问题如何解决

### ISSUE THREAD

**Issue by chaos-cn** [ja-netfilter/ja-netfilter#106]
写了个插件处理tomcat中的一些问题，修改原始逻辑为
`list.add(new MethodInsnNode(INVOKEVIRTUAL, "java/lang/String", "startsWith", "(Ljava/lang/String;)Z", false));`
并在setenv.sh中增加-javaagent
验证通过

但是仿照[plugin-dns](https://github.com/ja-netfilter/plugin-dns)增加自定义filter并修改原始代码调用时，会报ClassNotFoundException
` list.add(new MethodInsnNode(INVOKESTATIC, "com/janetfilter/plugins/myproject/MyFilter", "testCode", "(Ljava/lang/String;)Z", false));
`
查询了资料[深入理解Java ClassLoader及在 JavaAgent 中的应用](https://www.cnblogs.com/liboware/p/12500585.html)可能和这个有关，类加载这一块不太熟悉，想请教具体如何解决？

**Comment by RayGicEFL** [comment]
注意hideme插件会在所有`com.janetfilter`开头的类引用时返回`ClassNotFoundException`，以防止一些javaagent检测。请检查问题是否引起，具体方法是重命名`com.janetfilter.plugins.myproject`包，比如命名为`chaos.plugins.myproject`，不要以`com.janetfilter`开头

**Comment by RayGicEFL** [comment]
当然也有可能这并不是问题的原因，因为hideme只对forName方法进行了检测，不知道用asm会不会触发，不会java qwq

**Comment by chaos-cn** [comment]
> 注意hideme插件会在这种对`com.janetfilter`开头的类引用时返回`ClassNotFoundException`，以防止一些javaagent检测：
> 
> ```java
> forName("com.janetfilter..........
> ```
> 
> 请检查问题是否引起，具体方法是重命名`com.janetfilter.plugins.myproject`包，比如命名为`chaos.plugins.myproject`，不要以`com.janetfilter`开头

删除hideme插件或者调整包路径后验证成功，非常感谢！
