### ISSUE TITLE
Plugin License Authorization Failed.

### ISSUE THREAD

**Issue by HG-Group** [ja-netfilter/ja-netfilter#108]
Some plugins prompt License Authorization Failed.
MyBatis Log Plugin License Authorization Failed.
Regex Tool Plugin License Authorization Failed.

**Comment by pengzhile** [comment]
use code and DO NOT MODIFY THE FUCKING LICENSE DATE!

**Comment by HG-Group** [comment]
> use code and DO NOT MODIFY THE FUCKING LICENSE DATE!

![image](https://user-images.githubusercontent.com/79615037/159416545-ee0526cf-fb49-4686-bd0e-41471fc553f9.png)
![image](https://user-images.githubusercontent.com/79615037/159416600-10b867a1-c2cb-46b9-897b-7506a885b7b7.png)

**Comment by pengzhile** [comment]
so, what's the license expire date?

**Comment by HG-Group** [comment]
> 
![image](https://user-images.githubusercontent.com/79615037/159416957-85779255-8a29-4ff3-9544-70d58ce910cb.png)

**Comment by pengzhile** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/343491/159417043-73e42fbf-87dc-4dee-86d4-2bc397075f1d.png">

**Comment by HG-Group** [comment]
> <img alt="image" width="612" src="https://user-images.githubusercontent.com/343491/159417043-73e42fbf-87dc-4dee-86d4-2bc397075f1d.png">

So， need to re register after each expiration or the date be automatically updated every day

**Comment by pengzhile** [comment]
do you know what the `fallback license` means?
