### ISSUE TITLE
不确定是否兼容 Jdk17

### ISSUE THREAD

**Issue by colorsakura** [ja-netfilter/ja-netfilter#110]
jetbrains 更换 JBR 17 后，失效

**Comment by pengzhile** [comment]
未兼容

**Comment by pengzhile** [comment]
现在兼容了

**Comment by Slice-dd** [comment]
> 现在兼容了
你好，请问这是正常的么
![1653461322(1)](https://user-images.githubusercontent.com/19645852/170415533-3cb30d05-b0e5-4642-b592-57b00ca11907.jpg)
