### ISSUE TITLE
Package Checker plugin 貌似无效了

### ISSUE THREAD

**Issue by uxawseny** [ja-netfilter/ja-netfilter#117]
【idea版本】：
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022

【新版本有一项关于安全的特性，貌似不能使用】：

Security

Package Checker plugin ULTIMATE
IntelliJ IDEA 2022.1 can now detect vulnerabilities in Maven and Gradle dependencies used in your projects by checking across the [Checkmarx SCA Database](https://checkmarx.com/) and the [National Vulnerability Database](https://nvd.nist.gov/), thanks to the Package Сhecker plugin that is bundled with IntelliJ IDEA Ultimate.

Learn more in this [blog post](https://blog.jetbrains.com/idea/2022/04/ensure-greater-software-security-with-package-analysis-by-checkmarx-in-intellij-idea/).

请问有什么解决办法吗？

**Comment by pengzhile** [comment]
不知道你在说什么，有截图吗
