### ISSUE TITLE
Subscription is active until June 18, 2022

### ISSUE THREAD

**Issue by Slice-dd** [ja-netfilter/ja-netfilter#127]
版本：2022.1
使用方式，在idea64.exe.vmoptions中添加一行了如下代码：
`-javaagent:C:\Download\ja-netfilter\ja-netfilter.jar`
下面是about信息，请问这是正常的吗，谢谢。
![1653461322(1)](https://user-images.githubusercontent.com/19645852/170414320-78b2d6a7-d313-4882-b023-1b2e5440f146.jpg)
（ps：我昨天提的issues被删了吗）

**Comment by pengzhile** [comment]
有问题到置顶tg及时讨论
