### ISSUE TITLE
请问是否有靠谱的代理jb的教程？

### ISSUE THREAD

**Issue by wushu037** [ja-netfilter/ja-netfilter#128]
根据博客文章配置dns.conf、url.conf，然后在`goland.vmoptions`末尾加入`-javaagent:/Users/wushu/Develop/ja-netfilter/ja-netfilter.jar=jetbrains` 行不通
网上找的看起来需要配置的地方要多一些，还要填写activation code，担心不靠谱

**Comment by pengzhile** [comment]
看置顶issue

**Comment by wushu037** [comment]
> 看置顶issue

进telegram群吗，好的，谢谢
