### ISSUE TITLE
debug设置后，看不到插件的debug日志输出

### ISSUE THREAD

**Issue by jkingben** [ja-netfilter/ja-netfilter#27]
vmoptions设置：-javaagent:D:\Dev\JetBrains\ja-netfilter\ja-netfilter.jar

环境变量：JANF_DEBUG=1
vmoptions：-Djanf.debug=1

全都设置了，打开ide并没有日志输出，一点反应都没有，插件有生效吗

**Comment by hangsman** [comment]
环境变量：`JANF_CONFIG` = 你的 `janf_config.txt` 文件路径

**Comment by jkingben** [comment]
> 环境变量：`JANF_CONFIG` = 你的 `janf_config.txt` 文件路径

这跟debug的设置没关系，配置文件在插件目录

**Comment by brendan-lee** [comment]
用激活码激活，而不是试用

**Comment by githubwubicheng** [comment]
![image](https://user-images.githubusercontent.com/36580450/144730010-1c977cb8-d2fe-4793-901a-80f61ac8961c.png)
有啊

**Comment by githubwubicheng** [comment]
拦截了

**Comment by githubwubicheng** [comment]
可以阻止校验激活码，但是怎么让激活码可以一直使用呢

**Comment by hangsman** [comment]
> 可以阻止校验激活码，但是怎么让激活码可以一直使用呢

不能一直使用，激活码过期需要再找一个，一个月换一个激活码。
