### ISSUE TITLE
按照文档修改了却没有生效

### ISSUE THREAD

**Issue by withoutcat** [ja-netfilter/ja-netfilter#37]
修改了idea64.exe.vmoptions （无论是C盘里的，还是idea安装目录bin下面的）
配置文件也加了
但是进入idea以后，查看about，发现激活信息并没有按照MyMap所指定的信息显示，激活人也是为了进入idea所用的临时激活码
甚至我连插件生没生效都不知道。

**Comment by pengzhile** [comment]
名字都没变，当然是没生效。

**Comment by pengzhile** [comment]
怕是你配置文件名字是janf_config.txt.txt吧。
