### ISSUE TITLE
dlopen(libinstrument.dylib, 1): image not found

### ISSUE THREAD

**Issue by jiazhongyi** [ja-netfilter/ja-netfilter#38]
Hi, dbeaver uses the ja-netfilter jar package 

Error: 
Error occurred during initialization of VM
Could not find agent library instrument on the library path, with error: dlopen(libinstrument.dylib, 1): image not found
Module java.instrument may be missing from runtime image.

Git clone project code source,  mvn package, get jar package

dbeaver.ini:
...
-Xms128m
-Xmx512m
-XstartOnFirstThread
-javaagent:/Applications/DBeaverEE.app/Contents/MacOS/ja-netfilter.jar

do I have any configuration errors or other problems？

**Comment by pengzhile** [comment]
dbeaver 阉割了jre，自己下个jre替换
