### ISSUE TITLE
文章介绍是不是写错了

### ISSUE THREAD

**Issue by onekb** [ja-netfilter/ja-netfilter#39]
https://zhile.io/2021/11/29/ja-netfilter-javaagent-lib.html
https://zhile.io/2020/11/18/jetbrains-eval-reset-da33a93d.html
两篇文章里的“插件使用PHP编写，毕竟PHP是世界上最好的编程语言！”是不是写错了
明明是爪哇语言，为什么迫害我大PHP（狗头

**Comment by meiMingle** [comment]
没错（狗头

**Comment by pengzhile** [comment]
不可能写错，我只会PHP

**Comment by feng99** [comment]
作者是在故意嘲讽php而已.   哈哈

**Comment by pengzhile** [comment]
> 作者是在故意嘲讽php而已. 哈哈

我是PHP
从业者。你这样抹黑PHP，在我的群里是会被关3天小黑屋的。

**Comment by jhhd88** [comment]
> > 作者是在故意嘲讽php而已. 哈哈
> 
> 我是PHP 从业者。你这样抹黑PHP，在我的群里是会被关3天小黑屋的。

真的吗？我不信！（狗头

**Comment by zhangjunjie6b** [comment]
> 

刚嫖完彭工我证明是真的 （狗头

**Comment by zhangjunjie6b** [comment]
> > > 作者是在故意嘲讽php而已. 哈哈
> > 
> > 
> > 我是PHP 从业者。你这样抹黑PHP，在我的群里是会被关3天小黑屋的。
> 
> 真的吗？我不信！（狗头

刚嫖完彭工我证明是真的 （狗头
