### ISSUE TITLE
错误: 找不到或无法加载主类 com.janetfilter.core.Launcher

### ISSUE THREAD

**Issue by wz36125** [ja-netfilter/ja-netfilter#43]
原因: java.lang.ClassNotFoundException: com.janetfilter.core.Launcher
这是什么原因造成的呢？大佬能解答一下嘛

**Comment by lingyangcj** [comment]
> 原因: java.lang.ClassNotFoundException: com.janetfilter.core.Launcher 这是什么原因造成的呢？大佬能解答一下嘛

你好，请问你怎么解决的，我也有这个问题。
