### ISSUE TITLE
不确定HookClassName如何写插件

### ISSUE THREAD

**Issue by googleweb** [ja-netfilter/ja-netfilter#44]
我想修改实现了某个接口的类，但是具体类名不知道，如何开发插件。正常是通过ClassNode去判断接口信息的，接口信息中有就去修改这个接口的方法。可不可以增加一个HookInterfaceName的功能。

**Comment by pengzhile** [comment]
最好还是搞清楚类名，如果每个类都去使用ClassNode判断接口信息，将会极其影响性能。

**Comment by googleweb** [comment]
我已经收到您的信件!
