### ISSUE TITLE
配置好之后，图标启动不生效，bash启动则正常加载

### ISSUE THREAD

**Issue by DivinerWJ** [ja-netfilter/ja-netfilter#45]
我脚本启动会正常加载`janf_config.txt`中的配置信息，路径为`/Applications/IntelliJ IDEA.app/Contents/MacOS/idea`

但直接点击图标启动不会加载

**Comment by pengzhile** [comment]
我实在不建议文件/文件夹名字有中文。

**Comment by DivinerWJ** [comment]
> 

/Users/xxxx/Documents/ja_netfilter/ja-netfilter.jar

不会是`Documents`的问题吧，这个文件夹在访达中显示的是文稿，我修改试试

**Comment by pengzhile** [comment]
建议janf_config.txt和ja-netfilter.jar放在一个目录，不要额外配置

**Comment by DivinerWJ** [comment]
> 
已解决。

嗯 看了readme，是用了懒癌方法。放在了同一目录下。不是这个问题，的确是我上面提的那个问题，`Documents`在访达中显示的是`文稿`，虽然终端中的名字是`Documents`。

**Comment by DivinerWJ** [comment]
> 建议janf_config.txt和ja-netfilter.jar放在一个目录，不要额外配置

换了个路径，没用`Documents`文件夹。
