### ISSUE TITLE
mybatis log plugin cannot start due to startup

### ISSUE THREAD

**Issue by Charlee-du** [ja-netfilter/ja-netfilter#46]
Activation succeeded, but mybatis log plugin cannot start due to startup. 
MyBatis Log Plugin License Authorization Failed.
![微信截图_20211214141409](https://user-images.githubusercontent.com/37035916/145954091-1a71e381-3d6f-405e-9ba6-2aadbf76665b.png)

**Comment by pengzhile** [comment]
那么是谁让你把激活日期弄那么长的呢？
