### ISSUE TITLE
用过一段时间就会弹出要求登录JB

### ISSUE THREAD

**Issue by qomosoloto** [ja-netfilter/ja-netfilter#56]
很奇怪，用一段时间就会弹出登录JB账户，然后打开浏览器登录后再点激活才可以接着用。

**Comment by qomosoloto** [comment]
很奇怪，用一段时间就会弹出登录JB账户，然后打开浏览器登录后再点激活才可以接着用。

**Comment by pengzhile** [comment]
为什么要登录？

**Comment by highertq** [comment]
本来俩个都是到2099过期，一会是idea，一会是codewithme提示需要激活，只能找了一个激活码解决，时不时弹出，还是有些麻烦。

**Comment by pengzhile** [comment]
不会弹，你url 或 dns 插件没弄好。
