### ISSUE TITLE
求助~mac os 不可用

### ISSUE THREAD

**Issue by MyHtime** [ja-netfilter/ja-netfilter#57]
`ja-netfilter`文件位置: `/Users/user/Library/Application Support/JetBrains/ja-netfilter-all`
`idea.vmoptions` 位置：`/Users/user/Library/Application Support/JetBrains/IntelliJIdea2021.3`
配置内容：`-javaagent:/Users/user/Library/Application Support/JetBrains/ja-netfilter-all/ja-netfilter.jar`

idea正常启动后，仍然弹出激活窗口

求助

**Comment by pengzhile** [comment]
配完你不得有个码吗？
