### ISSUE TITLE
Where is MyMap plugin?

### ISSUE THREAD

**Issue by WhiteBite** [ja-netfilter/ja-netfilter#63]
I've seen in previous versions, the main swap functionality (for Intellij Idea) was based on the MyMap plugin. Is it not needed now?

**Comment by pengzhile** [comment]
读书成诗

**Comment by WhiteBite** [comment]
> 读书成诗

Unfortunately, I didn't quite get it. Can you explain?

**Comment by DatGuy1** [comment]
@WhiteBite https://github.com/zfkun/ja-netfilter-mymap-plugin/releases

**Comment by WhiteBite** [comment]
> @WhiteBite https://github.com/zfkun/ja-netfilter-mymap-plugin/releases

Thanks
