### ISSUE TITLE
IntelliJ IDEA doesn't run

### ISSUE THREAD

**Issue by 0xb4dc0d3x** [ja-netfilter/ja-netfilter#76]
Hi 
I'm Linux user and I want to use ja-netfilter:
for editing .vmoption file I use jetbrain toolbox and add the `-javaagent:/home/neo/janetfilter/ja-netfilter.jar`
to that .vmoption file
after saving I click on IntelliJ IDEA but nothing happens
but without `-javaagent:/home/neo/janetfilter/ja-netfilter.jar` program runs.
How should I fix that?

**Comment by pengzhile** [comment]
replace to the real path, you are not the “neo”

Saeed Khatami ***@***.***>于2022年1月4日 周二20:24写道：

**Comment by 0xb4dc0d3x** [comment]
Thank you, it works fine and well
