### ISSUE TITLE
linux 下面有问题

### ISSUE THREAD

**Issue by redseabay** [ja-netfilter/ja-netfilter#78]
ja-netfilter 2.0.1 + mymap 1.1.2, 同样的配置, windows 下面可以激活, linux 下面就不行. clion & goland 2021.2.3 2021.3 2021.3.2 都试过.

换成 ja-netfilter 1.0.2 + mymap 1.0.1 两个平台都可以.

os 是: debian 11, kde

**Comment by pengzhile** [comment]
但凡看了置顶issue都不会这么用吧
