### ISSUE TITLE
mymap插件一个很疑惑的“bug”

### ISSUE THREAD

**Issue by RayGicEFL** [ja-netfilter/ja-netfilter#82]
在`ja-netfilter-all.zip`的`config/mymap.conf`中可以看到配置文件是这样的：  
```
[MyMap]
EQUAL,licenseeName->MyMap
EQUAL,gracePeriodDays->100000
EQUAL,paidUpTo->2022-12-31
```  
所以为什么第二行是`licenseeName`而不是`licenseName`？问题就在于，`licenseeName`反倒能使MyMap工作；如果把其改为`licenseName`，MyMap就不会读取licenseName配置了。  
~~所以我就很不要脸地反编译了MyMap（逃（zhile大大不要打我求求了~~  
代码中并没有找到`licenseeName`字符串，但是找到了使`licenseName`配置为null的原因：  
`PutFilter`类中有这个方法：  
```java
public static Object testPut(Object k, Object v) {
    if (null == k) {
        return v;
    } else {
        return map.containsKey(k) ? map.get(k) : v;
    }
}
```
~~如果这真的是mymap的代码的话 建议zhile大大使用getOrDefault()而不是?:运算符~~
即当map中不存在key `k`的时候就会返回`v`，结合上面可知：  
当map中不存在key `licenseeName`时返回`null`  
然而我又发现唯一的testPut调用用的是asm，并且我从来没接触过asm所以……
贴上代码，看看有没有dalao说说这究竟是jetbrains ide的代码写错了(因为可能mymap只是直接把map传输给ide)还是mymap的bug：  
```java
        ClassReader reader = new ClassReader(classBytes);
        ClassNode node = new ClassNode(327680);
        reader.accept(node, 0);
        Iterator var6 = node.methods.iterator();

        while(var6.hasNext()) {
            MethodNode mn = (MethodNode)var6.next();
            if ("put".equals(mn.name) && "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;".equals(mn.desc)) {
                InsnList list = new InsnList();
                list.add(new VarInsnNode(25, 1));
                list.add(new VarInsnNode(25, 2));
                list.add(new MethodInsnNode(184, "in/jetbra/plugins/mymap/PutFilter", "testPut", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", false));
                list.add(new VarInsnNode(58, 2));
                mn.instructions.insert(list);
            }
        }

        ClassWriter writer = new ClassWriter(3);
        node.accept(writer);
```

**Comment by pengzhile** [comment]
其实。。。找个英汉词典查一下？

**Comment by RayGicEFL** [comment]
我他妈是傻逼。
>A licensee is any business, organization, or individual that has been granted legal permission by another entity to engage in an activity. The permission, or license, can be given on an express or implied basis.  
~~不过还是不明白 mymap这插件……究竟是个什么原理（不过zhile大大是绝对不会告诉我的 : (~~
~~对了 zhile大大为何不去看看我的pr呢（逃（哪来的迷之自信~~

**Comment by pengzhile** [comment]
> 我他妈是傻逼。
> 
> > A licensee is any business, organization, or individual that has been granted legal permission by another entity to engage in an activity. The permission, or license, can be given on an express or implied basis.
> 
> ~不过还是不明白 mymap这插件……究竟是个什么原理（不过zhile大大是绝对不会告诉我的 : (~ ~对了 zhile大大为何不去看看我的pr呢（逃（哪来的迷之自信~

先不急，正在筹备3.0

**Comment by RayGicEFL** [comment]
谢谢 xD
