### ISSUE TITLE
code invalid

### ISSUE THREAD

**Issue by feng99** [ja-netfilter/ja-netfilter#84]
idea vm  config

-Xmx4086m
-javaagent:E:/Java/soft/idea-jar/ja-netfilter.jar

from here copy one code
https://jetbra.in/1627c3d9-cc05-4b1d-b96d-cb824871c3a3.html

![image](https://user-images.githubusercontent.com/13182572/149279745-06b956c8-458b-47e3-b069-40ac6f4ac37a.png)

**Comment by pengzhile** [comment]
你既然贴了这个页面，为什么不download一下呢
