### ISSUE TITLE
FEATURE DISSCUSSION

### ISSUE THREAD

**Issue by karl-chanel** [ja-netfilter/ja-netfilter#9]

**Comment by karl-chanel** [comment]
reopen it when i get a deeper understanding

**Comment by karl-chanel** [comment]
sorry for bugging you,i didn't go deep about your whole project,just a quick glance,and just a normal question popped up,if the goal is to block auth url,i think we got a lot of blockers to use ,is it a optional choice or a must-have to use javaagent,and above that,how could blocking a url make it possible to get access to ide verification(sorry maybe that's not the goal),we still just got a 30-day key,ok i'll go back when i find more ,please correct me if i got it wrong @pengzhile

**Comment by zss823158062** [comment]
yeah,you are right

**Comment by linjunli01** [comment]
> sorry for bugging you,i didn't go deep about your whole project,just a quick glance,and just a normal question popped up,if the goal is to block auth url,i think we got a lot of blockers to use outside of the application itself,is it an optional choice or a must-have to use javaagent?,i can see that it can be used as a netfilter for a running jvm instance from the application itself not controlled by any proxy set by the os or other tools, and that's it (at least what i got),it's a good tool to manage the application's traffic,but how could blocking a url make it possible to get access to the ide verification(sorry maybe that's not the goal),we still just got a 30-day key,ok i'll go back when i find more ,please correct me if i got it wrong @pengzhile

there is somewhere someone share and update 30-day key

**Comment by pengzhile** [comment]
> sorry for bugging you,i didn't go deep about your whole project,just a quick glance,and just a normal question popped up,if the goal is to block auth url,i think we got a lot of blockers to use outside of the application itself,is it an optional choice or a must-have to use javaagent?,i can see that it can be used as a netfilter for a running jvm instance from the application itself not controlled by any proxy set by the os or other tools, and that's it (at least what i got),it's a good tool to manage the application's traffic,but how could blocking a url make it possible to get access to the ide verification(sorry maybe that's not the goal),we still just got a 30-day key,ok i'll go back when i find more ,please correct me if i got it wrong @pengzhile

The `power` plugin has been released, and now the missing corner of `ja-netfilter` have been completed. Now you can  take a look again.

**Comment by geyutong0209** [comment]
大佬们，能不能教教怎么用的

**Comment by samllStream** [comment]
配置了半天没生效

**Comment by jackbnx** [comment]
> > sorry for bugging you,i didn't go deep about your whole project,just a quick glance,and just a normal question popped up,if the goal is to block auth url,i think we got a lot of blockers to use outside of the application itself,is it an optional choice or a must-have to use javaagent?,i can see that it can be used as a netfilter for a running jvm instance from the application itself not controlled by any proxy set by the os or other tools, and that's it (at least what i got),it's a good tool to manage the application's traffic,but how could blocking a url make it possible to get access to the ide verification(sorry maybe that's not the goal),we still just got a 30-day key,ok i'll go back when i find more ,please correct me if i got it wrong @pengzhile
> 
> The `power` plugin has been released, and now the missing corners of `ja-netfilter` have been completed. Now you can take a look again.

@pengzhile Thank you so much for your hard work. The issue is, we don't understand anything. How does this `power` plugin work? There's no explanation or documentation anywhere. I do understand you're trying to avoid any forceful takedowns from the companies we don't wanna mention here. But some tutorials would really help.

**Comment by linjunli01** [comment]
我已经没用了，订阅了全家桶..,其它的，我只能说，多留意作者的另一个网站

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年12月30日 16:29
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ja-netfilter/ja-netfilter] FEATURE DISSCUSSION (Issue #9)


配置了半天没生效

―
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fja-netfilter%2Fja-netfilter%2Fissues%2F9%23issuecomment-1002923821&data=04%7C01%7C%7C2e32a368e2de4d46ea2808d9cb6e840f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764497802478892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z5yp6ck8Sr%2FY9CRkLGPAt00gwIHyeEnf6ot5ROTFEmA%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIPLKUK6QUBBVE7POCFANLDUTQJ7DANCNFSM5JCVUGIQ&data=04%7C01%7C%7C2e32a368e2de4d46ea2808d9cb6e840f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764497802478892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nJeBIO%2Fv%2FctW9YI%2Bl5FVYMKRFZf7sDrBD76YERB7jvE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2e32a368e2de4d46ea2808d9cb6e840f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764497802478892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9KVttR1bhbDk2wnNw6ubK4z1%2F6o5i6iKIoah1N%2B0Liw%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2e32a368e2de4d46ea2808d9cb6e840f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764497802478892%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cKRqKRClOEU9ywO%2BbnTnwfbu4Fj506fUuuJqvl9WlYY%3D&reserved=0>.

**Comment by hisaner** [comment]
The function of power conf is not described in the document

**Comment by crazyserb** [comment]
I'm sorry, but this thing is useless.

Zero documentation on how to use any of this on Windows, 

Zero documentation or explanation on how to compile any of this on Windows.

How to set up paths in vmoptions file (relative or absolute) on Windows.

Nothing.

Let us know when you come up with a usable version of any of this.

Thanks.
