### ISSUE TITLE
希望在plugin-Debug中能加一个dumpFile的功能，方便查看插桩字节码

### ISSUE THREAD

**Issue by Nasller** [ja-netfilter/ja-netfilter#90]
如题

**Comment by pengzhile** [comment]
plugin-debug？在哪？

**Comment by Nasller** [comment]
额，其实就是想有一个参数可以直接生成文件，可能我描述不清楚 :)

**Comment by pengzhile** [comment]
> 额，其实就是想有一个参数可以直接生成文件，可能我描述不清楚 :)

哦，我考虑考虑怎么弄比较好。

**Comment by Nasller** [comment]
> > 额，其实就是想有一个参数可以直接生成文件，可能我描述不清楚 :)
> 
> 哦，我考虑考虑怎么弄比较好。

嗯，感谢，省的写调试信息

**Comment by pengzhile** [comment]
> > > 额，其实就是想有一个参数可以直接生成文件，可能我描述不清楚 :)
> > 
> > 
> > 哦，我考虑考虑怎么弄比较好。
> 
> 嗯，感谢，省的写调试信息

试试新出的`plugin-dump`插件

**Comment by Nasller** [comment]
可以了，无敌
