### ISSUE TITLE
最新版本无法使用    It can be used on the latest version of pycharm

### ISSUE THREAD

**Issue by henryji33** [ja-netfilter/ja-netfilter#95]
Pycharm更新到2021.3.2后似乎无法使用
It seems that somethings went wrong after apdating pycharm by 2021.3.2

**Comment by pengzhile** [comment]
实测能用，自己检查一下吧。

**Comment by henryji33** [comment]
我找到解决方法了
I've found the solution
只需下载2.2.2版本即可
all you have to do is to download the 2.2.2version

**Comment by henryji33** [comment]
> 实测能用，自己检查一下吧。

不知什么情况，2.2.3版本pycharm提示无法连接，但是2.2.2版本成功。
